module.exports.brands = [
    'Gong Cha',
    'Kung Fu Tea',
    'Tiger Sugar',
    'Bambu',
    'Coco',
    'Biju',
    'Mooboo',
    'Xing Fu Tang',
    'Dragon Cat Cafe',
    'Chatime',
    'Dont yell at me',
    'Happy Lemon',
    'The Alley',
    'Sharetea',
    'Boba Guys',
    'Yi Fang',
    'TP Tea',
    'Tapioca Express'
]

module.exports.description = [
    'Enjoy a tranquil escape into the world of milk teas, where soothing blends and serene surroundings create the perfect respite.',
    'Indulge in the dreamy textures of milk teas that whisk you away to a realm of creamy delight and comforting warmth.',
    'Immerse yourself in the symphony of chai, where carefully crafted milk teas harmonize to create a delightful and balanced experience.',
    'Dive into a sea of tapioca pearls and rich tea flavors, where the delightful combination of textures makes each sip an adventure.',
    'Find peace in simplicity as you savor the zen-like atmosphere and delicate notes of milk tea in this cozy teahouse.',
    'Elevate your tea experience with a curated collection of regal milk teas, each sip a journey into refined taste.',
    'Let the subtle melodies of flavor serenade your senses as you unwind with a cup of meticulously crafted milk tea.',
    'Embark on a journey of velvety indulgence at this lounge, where the artistry of tea brewing meets a smooth, luxurious experience.',
    'Experience the joy of bubbles in every cup, where effervescence and rich flavors come together in perfect harmony.',
    'Encounter the mystique of secret tea blends in a cozy atmosphere, where every cup is a unique and enchanting experience.',
    'Dance with delightful tea flavors in a tucked-away nook, where the rhythmic essence of milk tea adds a touch of excitement.',
    'Cascade into sweetness with a caramel-infused tea experience, where each cup is a delightful journey down a flavorful waterfall.',
    'Seek solace in the comforting embrace of milk tea, creating a retreat where relaxation and flavor intertwine.',
    'Immerse yourself in tradition with golden-hued teas, where time-honored recipes take center stage in a comforting tea environment.',
    'Discover joy in every sip at this cheerful spot, where happiness is brewed into every drop of their delightful milk teas.',
    'Escape into the cool oasis of frothy milk teas, where each cup is a refreshing and flavorful journey.',
    'Delight your senses with the aroma of tea and the chewy pearls that make each cup a sensory experience.',
    'Join the symphony of tea flavors, where each cup is a harmonious note in the composition of your perfect drink.',
    'Indulge in sophistication with spiced teas, where elegance and flavor converge for a refined palate.',
]